insert into categorias (nombre) values ('Compensation Analyst');
insert into categorias (nombre) values ('Assistant Media Planner');
insert into categorias (nombre) values ('Project Manager');
insert into categorias (nombre) values ('Quality Engineer');
insert into categorias (nombre) values ('Systems Administrator II');
insert into categorias (nombre) values ('Senior Developer');
insert into categorias (nombre) values ('Information Systems Manager');
insert into categorias (nombre) values ('Financial Advisor');
insert into categorias (nombre) values ('Software Test Engineer I');
insert into categorias (nombre) values ('VP Product Management');
insert into categorias (nombre) values ('Junior Executive');
insert into categorias (nombre) values ('Software Engineer IV');
insert into categorias (nombre) values ('Budget/Accounting Analyst II');
insert into categorias (nombre) values ('Safety Technician IV');
insert into categorias (nombre) values ('Dental Hygienist');
insert into categorias (nombre) values ('Design Engineer');
insert into categorias (nombre) values ('Geological Engineer');
insert into categorias (nombre) values ('Senior Cost Accountant');
insert into categorias (nombre) values ('VP Accounting');
insert into categorias (nombre) values ('Senior Financial Analyst');
insert into categorias (nombre) values ('Human Resources Assistant II');
insert into categorias (nombre) values ('Human Resources Manager');
insert into categorias (nombre) values ('Pharmacist');
insert into categorias (nombre) values ('Chief Design Engineer');
insert into categorias (nombre) values ('Help Desk Technician');
insert into categorias (nombre) values ('Financial Analyst');
insert into categorias (nombre) values ('Graphic Designer');
insert into categorias (nombre) values ('Librarian');
insert into categorias (nombre) values ('Nurse');
insert into categorias (nombre) values ('Analog Circuit Design manager');
insert into categorias (nombre) values ('Software Test Engineer I');
insert into categorias (nombre) values ('Account Coordinator');
insert into categorias (nombre) values ('Media Manager II');
insert into categorias (nombre) values ('Systems Administrator I');
insert into categorias (nombre) values ('Structural Engineer');
insert into categorias (nombre) values ('Health Coach I');
insert into categorias (nombre) values ('Sales Associate');
insert into categorias (nombre) values ('Analog Circuit Design manager');
insert into categorias (nombre) values ('Technical Writer');
insert into categorias (nombre) values ('Financial Advisor');
insert into categorias (nombre) values ('Internal Auditor');
insert into categorias (nombre) values ('General Manager');
insert into categorias (nombre) values ('Administrative Assistant IV');
insert into categorias (nombre) values ('Design Engineer');
insert into categorias (nombre) values ('categoriasbase Administrator II');
insert into categorias (nombre) values ('General Manager');
insert into categorias (nombre) values ('Tax Accountant');
insert into categorias (nombre) values ('Associate Professor');
insert into categorias (nombre) values ('Senior Editor');
insert into categorias (nombre) values ('Accountant I');
insert into categorias (nombre) values ('Help Desk Technician');
insert into categorias (nombre) values ('Mechanical Systems Engineer');
insert into categorias (nombre) values ('Technical Writer');
insert into categorias (nombre) values ('Senior Financial Analyst');
insert into categorias (nombre) values ('Systems Administrator III');
insert into categorias (nombre) values ('Software Engineer I');
insert into categorias (nombre) values ('Desktop Support Technician');
insert into categorias (nombre) values ('Junior Executive');
insert into categorias (nombre) values ('Chief Design Engineer');
insert into categorias (nombre) values ('Social Worker');
insert into categorias (nombre) values ('Design Engineer');
insert into categorias (nombre) values ('Environmental Specialist');
insert into categorias (nombre) values ('Tax Accountant');
insert into categorias (nombre) values ('Tax Accountant');
insert into categorias (nombre) values ('Administrative Officer');
insert into categorias (nombre) values ('Electrical Engineer');
insert into categorias (nombre) values ('Operator');
insert into categorias (nombre) values ('Health Coach III');
insert into categorias (nombre) values ('Marketing Assistant');
insert into categorias (nombre) values ('Desktop Support Technician');
insert into categorias (nombre) values ('Research Assistant IV');
insert into categorias (nombre) values ('VP Marketing');
insert into categorias (nombre) values ('Software Test Engineer I');
insert into categorias (nombre) values ('VP Sales');
insert into categorias (nombre) values ('Account Executive');
insert into categorias (nombre) values ('Mechanical Systems Engineer');
insert into categorias (nombre) values ('Payment Adjustment Coordinator');
insert into categorias (nombre) values ('Product Engineer');
insert into categorias (nombre) values ('Electrical Engineer');
insert into categorias (nombre) values ('Marketing Manager');
insert into categorias (nombre) values ('Senior Quality Engineer');
insert into categorias (nombre) values ('Assistant Professor');
insert into categorias (nombre) values ('Actuary');
insert into categorias (nombre) values ('Senior Quality Engineer');
insert into categorias (nombre) values ('Compensation Analyst');
insert into categorias (nombre) values ('Executive Secretary');
insert into categorias (nombre) values ('Executive Secretary');
insert into categorias (nombre) values ('Research Associate');
insert into categorias (nombre) values ('GIS Technical Architect');
insert into categorias (nombre) values ('Assistant Media Planner');
insert into categorias (nombre) values ('Marketing Manager');
insert into categorias (nombre) values ('Statistician III');
insert into categorias (nombre) values ('Engineer IV');
insert into categorias (nombre) values ('Associate Professor');
insert into categorias (nombre) values ('Editor');
insert into categorias (nombre) values ('VP Product Management');
insert into categorias (nombre) values ('Quality Engineer');
insert into categorias (nombre) values ('VP Accounting');
insert into categorias (nombre) values ('Product Engineer');
insert into categorias (nombre) values ('Actuary');
